### PR TITLE
fixes issue with vite.config.ts base

### PR DESCRIPTION
**Pull request by drewpate**
<Update pull_request_template.md to change this template>
<Delete any sections below that are not applicable>

# Description

Issue: #37

- [ ] Change 1 Updated the base from '/learnjs/' to just '/' to match the base URL in App.tsx

# Screenshots
Screen Shot 2023-07-10 at 8 56 41 PM
Screen Shot 2023-07-10 at 8 56 51 PM

# Notes

Not sure if there's a way to get the baseurl to work a different way but this fixed the issue locally.

### CODE REVIEW

**Comment by drewpate** [comment]
@HudsonGraeme @codeTrackLift I'm not sure why there were so many files changes. It could be that prettier or VSCode messed with them.

**Review by codeTrackLift — CHANGES_REQUESTED** [review]
Looks like there's a `.next` folder that made its way into this PR?  Should this be in the `.gitignore` or removed from the build since we are pivoting to `Vite`?

**Comment by drewpate** [comment]
> Looks like there's a `.next` folder that made its way into this PR? Should this be in the `.gitignore` or removed from the build since we are pivoting to `Vite`?

> @codeTrackLift I've added *.next into the .gitignore file. Curious to see if we will have the blank page fixed after we merge.

**Comment by codeTrackLift** [comment]
Thanks @drewpate. Looks like the `.next` file is still part of the PR and the commit appears to add 18k+ lines...

Screenshot 2023-07-13 at 8 14 44 PM

**Comment by drewpate** [comment]
> Thanks @drewpate. Looks like the `.next` file is still part of the PR and the commit appears to add 18k+ lines...
> 
> Screenshot 2023-07-13 at 8 14 44 PM

> @codeTrackLift I'm seeing this now too. At the point I'm pretty stuck, not sure how to move forward.

**Comment by codeTrackLift** [comment]
No worries, an easy solution is to just close this branch and open a new one with just the intended change.

**Pull request closed without merging**
