### PR TITLE
bug: fix blank page and base URL in prod

### LINKED ISSUE #37: Blank Page
The GitHub Page is coming up blank.
When running locally it. Looks like there is an issue with the base url. Take a look at the vite.config.ts file and the base Route in App.tsx

### PR DESCRIPTION
**Pull request by HudsonGraeme**
<Update pull_request_template.md to change this template>
Resolves #37 

<Delete any sections below that are not applicable>

# Description

Issue: #37

- [x] Added check for environment to dynamically select base URL

# Screenshots

<details>
 <summary>Click here for screenshots</summary>

N/A

</details>

# Notes

On localhost, the routing is based at `/`, but on GH pages the routing is based at `/learnjs/`. To allow the app to run both locally and in prod, I added a check for an environment variable automatically set by node at buildtime called `NODE_ENV`. When building in dev mode for local testing, the variable will be automatically set to `development`. When building the project for deployment, it'll automatically populate as `production`.

### CODE REVIEW

**Comment by HudsonGraeme** [comment]
Thanks to @drewpate for finding the issue that caused the blank page! This is based on his fix.

**Review by drewpate — APPROVED** [review]
@HudsonGraeme this is great ! Thanks so much. Looks good.

**Review by codeTrackLift — APPROVED** [review]
LGTM, thanks @HudsonGraeme! 🚀

**Comment by HudsonGraeme** [comment]
:joy: That still didn't work... Troubleshooting now

**Pull request merged**
